language: generic
sudo: required
services: 
  - docker

env:
  global: 
    - SERVER_PORT=5000
    - MONGO_HOST=mongodb
    - MONGO_PORT=27017
    - DB_NAME=messages-db

jobs: 
  include:
    - stage: "Tests"
      name: "Tests all"
      script: ./scripts/test.sh
